/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view2;

import database.model.Admin;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import view.ToolFrame;
import javax.swing.JInternalFrame;
import view3.Category;
//import view3.Category;
import static view3.Category.userObject;

/**
 *
 * @author Administrator
 */
public class SeetingView extends javax.swing.JFrame {

    /**
     * Creates new form SeetingView
     */
    public SeetingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){ @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon img = new ImageIcon("E:\\新建文件夹 (2)\\y.jpg");
                img.paintIcon(this, g, 0, 0);
            }};
            jMenuBar1 = new javax.swing.JMenuBar();
            AccountManageMenu = new javax.swing.JMenu();
            ChangeUserNameMenuItem = new javax.swing.JMenuItem();
            ChangePassWordMenuItem = new javax.swing.JMenuItem();
            jMenu2 = new javax.swing.JMenu();
            ContactUsMenuItem = new javax.swing.JMenuItem();
            AboutUsMenuItem = new javax.swing.JMenuItem();
            jMenu3 = new javax.swing.JMenu();
            jMenuItem1 = new javax.swing.JMenuItem();
            jMenuItem4 = new javax.swing.JMenuItem();
            jMenu1 = new javax.swing.JMenu();
            jMenuItem2 = new javax.swing.JMenuItem();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 903, Short.MAX_VALUE)
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 480, Short.MAX_VALUE)
            );

            jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));

            AccountManageMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/系统管理.png"))); // NOI18N
            AccountManageMenu.setText(" Account Managemment  ");
            AccountManageMenu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

            ChangeUserNameMenuItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            ChangeUserNameMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/用户.png"))); // NOI18N
            ChangeUserNameMenuItem.setText("Change Username");
            ChangeUserNameMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ChangeUserNameMenuItemActionPerformed(evt);
                }
            });
            AccountManageMenu.add(ChangeUserNameMenuItem);

            ChangePassWordMenuItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            ChangePassWordMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/密码.png"))); // NOI18N
            ChangePassWordMenuItem.setText("Change Password");
            ChangePassWordMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ChangePassWordMenuItemActionPerformed(evt);
                }
            });
            AccountManageMenu.add(ChangePassWordMenuItem);

            jMenuBar1.add(AccountManageMenu);

            jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/关于我们.png"))); // NOI18N
            jMenu2.setText("About Us  ");
            jMenu2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
            jMenu2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu2ActionPerformed(evt);
                }
            });

            ContactUsMenuItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            ContactUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/联系.png"))); // NOI18N
            ContactUsMenuItem.setText("Contact Us");
            jMenu2.add(ContactUsMenuItem);

            AboutUsMenuItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            AboutUsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/关于我们.png"))); // NOI18N
            AboutUsMenuItem.setText("About us");
            AboutUsMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AboutUsMenuItemActionPerformed(evt);
                }
            });
            jMenu2.add(AboutUsMenuItem);

            jMenuBar1.add(jMenu2);

            jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/其它.png"))); // NOI18N
            jMenu3.setText("Others   ");
            jMenu3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

            jMenuItem1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/语言.png"))); // NOI18N
            jMenuItem1.setText("Language Setting");
            jMenu3.add(jMenuItem1);

            jMenuItem4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/联系我们.png"))); // NOI18N
            jMenuItem4.setText("Contact Us");
            jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem4ActionPerformed(evt);
                }
            });
            jMenu3.add(jMenuItem4);

            jMenuBar1.add(jMenu3);

            jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/主页32.png"))); // NOI18N
            jMenu1.setText("Home page");
            jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

            jMenuItem2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/主页32.png"))); // NOI18N
            jMenuItem2.setText("Home page");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem2);

            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ChangeUserNameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUserNameMenuItemActionPerformed
        // TODO add your handling code here:
        changeUserName(evt);
    }//GEN-LAST:event_ChangeUserNameMenuItemActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jMenu2ActionPerformed

    private void AboutUsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuItemActionPerformed
        // TODO add your handling code here:
        aboutUs(evt);
    }//GEN-LAST:event_AboutUsMenuItemActionPerformed

    private void ChangePassWordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassWordMenuItemActionPerformed
        // TODO add your handling code here:
        changePassWord(evt);
    }//GEN-LAST:event_ChangePassWordMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Category two = new Category(userObject);
        two.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeetingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeetingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeetingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeetingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeetingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsMenuItem;
    private javax.swing.JMenu AccountManageMenu;
    private javax.swing.JMenuItem ChangePassWordMenuItem;
    private javax.swing.JMenuItem ChangeUserNameMenuItem;
    private javax.swing.JMenuItem ContactUsMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void changeUserName(ActionEvent evt) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        // this.setVisible(true);
        changeUserName userName = new changeUserName();
        userName.setVisible(true);
    }

    private void aboutUs(ActionEvent evt) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

        //采用Java 调用系统浏览器打开制定
        try {
            URI uri = new URI("http://flo.flinders.edu.au/");
            Desktop.getDesktop().browse(uri);
            //Runtime.getRuntime().exec("explorer http://flo.flinders.edu.au/");
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

    private void changePassWord(ActionEvent evt) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        changePassWord passWord = new changePassWord();
        passWord.setVisible(true);
    }
}
